/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The ApiError model module.
* @module Model/ApiError
* @version 1.0.0
*/
module.exports = class ApiError{
    /**
    * Constructs a new <code>ApiError</code>.
    * @alias module:Model/ApiError
    * @class
    */

    constructor() {
        
        
        
        
    }

    /**
    * Constructs a <code>ApiError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/ApiError} obj Optional instance to populate.
    * @return {module:Model/ApiError} The populated <code>ApiError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiError();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'Number');
            }
            if (data.hasOwnProperty('documentation')) {
                obj['documentation'] = ApiClient.convertToType(data['documentation'], 'String');
            }
        }
        return obj;
    }

    /**
    * The error message
    * @member {String} message
    */
    message = undefined;
    /**
    * The specific error code
    * @member {Number} errorCode
    */
    errorCode = undefined;
    /**
    * Any specific documentation for the error
    * @member {String} documentation
    */
    documentation = undefined;








}


