/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The Attributes model module.
* @module Model/Attributes
* @version 1.0.0
*/
module.exports = class Attributes{
    /**
    * Constructs a new <code>Attributes</code>.
    * @alias module:Model/Attributes
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>Attributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/Attributes} obj Optional instance to populate.
    * @return {module:Model/Attributes} The populated <code>Attributes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Attributes();

            
            
            

        }
        return obj;
    }









}


