/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The CreateSmsDefinitionSubscriptions model module.
* @module Model/CreateSmsDefinitionSubscriptions
* @version 1.0.0
*/
module.exports = class CreateSmsDefinitionSubscriptions{
    /**
    * Constructs a new <code>CreateSmsDefinitionSubscriptions</code>.
    * @alias module:Model/CreateSmsDefinitionSubscriptions
    * @class
    * @param shortCode {String} The short code for the mobile transmissions for each message on this definition.
    * @param countryCode {String} The country code associated with the shortCode for the mobile transmissions for each message on this definition.
    */

    constructor(shortCode, countryCode) {
        
        // verify the required parameter 'shortCode' is set
        if(shortCode === undefined || shortCode === null){
            throw new InvalidModelException('"shortCode" is a required property for CreateSmsDefinitionSubscriptions and cannot be undefined or null');
        }
        this['shortCode'] = shortCode;
        
        // verify the required parameter 'countryCode' is set
        if(countryCode === undefined || countryCode === null){
            throw new InvalidModelException('"countryCode" is a required property for CreateSmsDefinitionSubscriptions and cannot be undefined or null');
        }
        this['countryCode'] = countryCode;
        
        
        
    }

    /**
    * Constructs a <code>CreateSmsDefinitionSubscriptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/CreateSmsDefinitionSubscriptions} obj Optional instance to populate.
    * @return {module:Model/CreateSmsDefinitionSubscriptions} The populated <code>CreateSmsDefinitionSubscriptions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSmsDefinitionSubscriptions();

            
            
            

            if (data.hasOwnProperty('shortCode')) {
                obj['shortCode'] = ApiClient.convertToType(data['shortCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('keyword')) {
                obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
            }
            if (data.hasOwnProperty('autoAddSubscriber')) {
                obj['autoAddSubscriber'] = ApiClient.convertToType(data['autoAddSubscriber'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The short code for the mobile transmissions for each message on this definition.
    * @member {String} shortCode
    */
    shortCode = undefined;
    /**
    * The country code associated with the shortCode for the mobile transmissions for each message on this definition.
    * @member {String} countryCode
    */
    countryCode = undefined;
    /**
    * The keyword used to track messages.
    * @member {String} keyword
    */
    keyword = undefined;
    /**
    * Permits adding a recipient as subscriber against the shortCode using contactKey. When false, the message is rejected if contactKey does not exist as a subscriber. Default is true.
    * @member {Boolean} autoAddSubscriber
    * @default true
    */
    autoAddSubscriber = true;








}


