/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The CreateEmailDefinitionSubscriptions model module.
* @module Model/CreateEmailDefinitionSubscriptions
* @version 1.0.0
*/
module.exports = class CreateEmailDefinitionSubscriptions{
    /**
    * Constructs a new <code>CreateEmailDefinitionSubscriptions</code>.
    * @alias module:Model/CreateEmailDefinitionSubscriptions
    * @class
    * @param list {String} Marketing Cloud external key of the list or all subscribers. Contains the subscriber keys and profile attributes.
    */

    constructor(list) {
        
        // verify the required parameter 'list' is set
        if(list === undefined || list === null){
            throw new InvalidModelException('"list" is a required property for CreateEmailDefinitionSubscriptions and cannot be undefined or null');
        }
        this['list'] = list;
        
        
        
        
    }

    /**
    * Constructs a <code>CreateEmailDefinitionSubscriptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/CreateEmailDefinitionSubscriptions} obj Optional instance to populate.
    * @return {module:Model/CreateEmailDefinitionSubscriptions} The populated <code>CreateEmailDefinitionSubscriptions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateEmailDefinitionSubscriptions();

            
            
            

            if (data.hasOwnProperty('list')) {
                obj['list'] = ApiClient.convertToType(data['list'], 'String');
            }
            if (data.hasOwnProperty('dataExtension')) {
                obj['dataExtension'] = ApiClient.convertToType(data['dataExtension'], 'String');
            }
            if (data.hasOwnProperty('autoAddSubscriber')) {
                obj['autoAddSubscriber'] = ApiClient.convertToType(data['autoAddSubscriber'], 'Boolean');
            }
            if (data.hasOwnProperty('updateSubscriber')) {
                obj['updateSubscriber'] = ApiClient.convertToType(data['updateSubscriber'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Marketing Cloud external key of the list or all subscribers. Contains the subscriber keys and profile attributes.
    * @member {String} list
    */
    list = undefined;
    /**
    * Marketing Cloud external key of the triggered send data extension. Each request inserts as a new row in the data extension.
    * @member {String} dataExtension
    */
    dataExtension = undefined;
    /**
    * Adds the recipient’s email address and contact key as a subscriber key to subscriptions.list. Default is true.
    * @member {Boolean} autoAddSubscriber
    * @default true
    */
    autoAddSubscriber = true;
    /**
    * Updates the recipient’s contact key as a subscriber key with the provided email address and profile attributes to subscriptions.list. Default is true.
    * @member {Boolean} updateSubscriber
    */
    updateSubscriber = undefined;








}


