/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');
const Campaign = require ('./Campaign');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The GetAllCampaignsResponse model module.
* @module Model/GetAllCampaignsResponse
* @version 1.0.0
*/
module.exports = class GetAllCampaignsResponse{
    /**
    * Constructs a new <code>GetAllCampaignsResponse</code>.
    * @alias module:Model/GetAllCampaignsResponse
    * @class
    */

    constructor() {
        
        
        
        
        
    }

    /**
    * Constructs a <code>GetAllCampaignsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/GetAllCampaignsResponse} obj Optional instance to populate.
    * @return {module:Model/GetAllCampaignsResponse} The populated <code>GetAllCampaignsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAllCampaignsResponse();

            
            
            

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Campaign]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:Model/Campaign>} items
    */
    items = undefined;
    /**
    * Number of pages
    * @member {Number} count
    */
    count = undefined;
    /**
    * Page number to return.
    * @member {Number} page
    */
    page = undefined;
    /**
    * Number of campaigns, which are array elements, to return per paged response.
    * @member {Number} pageSize
    */
    pageSize = undefined;








}


