/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');
const GetDefinitionsNotSentToRecipientsMessageInfo = require ('./GetDefinitionsNotSentToRecipientsMessageInfo');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The GetDefinitionsNotSentToRecipientsMessage model module.
* @module Model/GetDefinitionsNotSentToRecipientsMessage
* @version 1.0.0
*/
module.exports = class GetDefinitionsNotSentToRecipientsMessage{
    /**
    * Constructs a new <code>GetDefinitionsNotSentToRecipientsMessage</code>.
    * @alias module:Model/GetDefinitionsNotSentToRecipientsMessage
    * @class
    */

    constructor() {
        
        
        
        
        
        
        
        
    }

    /**
    * Constructs a <code>GetDefinitionsNotSentToRecipientsMessage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/GetDefinitionsNotSentToRecipientsMessage} obj Optional instance to populate.
    * @return {module:Model/GetDefinitionsNotSentToRecipientsMessage} The populated <code>GetDefinitionsNotSentToRecipientsMessage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDefinitionsNotSentToRecipientsMessage();

            
            
            

            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('statusMessage')) {
                obj['statusMessage'] = ApiClient.convertToType(data['statusMessage'], 'String');
            }
            if (data.hasOwnProperty('eventCategoryType')) {
                obj['eventCategoryType'] = ApiClient.convertToType(data['eventCategoryType'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('definitionKey')) {
                obj['definitionKey'] = ApiClient.convertToType(data['definitionKey'], 'String');
            }
            if (data.hasOwnProperty('eventID')) {
                obj['eventID'] = ApiClient.convertToType(data['eventID'], 'Number');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = GetDefinitionsNotSentToRecipientsMessageInfo.constructFromObject(data['info']);
            }
        }
        return obj;
    }

    /**
    * The specific status code
    * @member {Number} statusCode
    */
    statusCode = undefined;
    /**
    * The specific status message
    * @member {String} statusMessage
    */
    statusMessage = undefined;
    /**
    * The status of the message
    * @member {String} eventCategoryType
    */
    eventCategoryType = undefined;
    /**
    * The date the ...
    * @member {Date} timestamp
    */
    timestamp = undefined;
    /**
    * Unique, user-generated key to access the definition object.
    * @member {String} definitionKey
    */
    definitionKey = undefined;
    /**
    * 
    * @member {Number} eventID
    */
    eventID = undefined;
    /**
    * @member {module:Model/GetDefinitionsNotSentToRecipientsMessageInfo} info
    */
    info = undefined;








}


