/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');
const GetDefinitionsNotSentToRecipientsMessage = require ('./GetDefinitionsNotSentToRecipientsMessage');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The GetDefinitionsNotSentToRecipientsResponse model module.
* @module Model/GetDefinitionsNotSentToRecipientsResponse
* @version 1.0.0
*/
module.exports = class GetDefinitionsNotSentToRecipientsResponse{
    /**
    * Constructs a new <code>GetDefinitionsNotSentToRecipientsResponse</code>.
    * @alias module:Model/GetDefinitionsNotSentToRecipientsResponse
    * @class
    */

    constructor() {
        
        
        
        
        
        
    }

    /**
    * Constructs a <code>GetDefinitionsNotSentToRecipientsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/GetDefinitionsNotSentToRecipientsResponse} obj Optional instance to populate.
    * @return {module:Model/GetDefinitionsNotSentToRecipientsResponse} The populated <code>GetDefinitionsNotSentToRecipientsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDefinitionsNotSentToRecipientsResponse();

            
            
            

            if (data.hasOwnProperty('lastEventID')) {
                obj['lastEventID'] = ApiClient.convertToType(data['lastEventID'], 'Number');
            }
            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [GetDefinitionsNotSentToRecipientsMessage]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Event ID from which you want the response to start. To obtain the initial event ID, submit a request without a lastEventId. The events in the response are listed top to bottom from oldest to newest
    * @member {Number} lastEventID
    */
    lastEventID = undefined;
    /**
    * 
    * @member {Array.<module:Model/GetDefinitionsNotSentToRecipientsMessage>} messages
    */
    messages = undefined;
    /**
    * Number of pages
    * @member {Number} count
    */
    count = undefined;
    /**
    * The ID of the request
    * @member {String} requestId
    */
    requestId = undefined;
    /**
    * Number of definitions, which are array elements, to return per paged response.
    * @member {Number} pageSize
    */
    pageSize = undefined;








}


