/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');
const SendDefinitionResponseItem = require ('./SendDefinitionResponseItem');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The SendDefinitionToMultipleRecipientsResponse model module.
* @module Model/SendDefinitionToMultipleRecipientsResponse
* @version 1.0.0
*/
module.exports = class SendDefinitionToMultipleRecipientsResponse{
    /**
    * Constructs a new <code>SendDefinitionToMultipleRecipientsResponse</code>.
    * @alias module:Model/SendDefinitionToMultipleRecipientsResponse
    * @class
    */

    constructor() {
        
        
        
        
        
    }

    /**
    * Constructs a <code>SendDefinitionToMultipleRecipientsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/SendDefinitionToMultipleRecipientsResponse} obj Optional instance to populate.
    * @return {module:Model/SendDefinitionToMultipleRecipientsResponse} The populated <code>SendDefinitionToMultipleRecipientsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendDefinitionToMultipleRecipientsResponse();

            
            
            

            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('errorcode')) {
                obj['errorcode'] = ApiClient.convertToType(data['errorcode'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('responses')) {
                obj['responses'] = ApiClient.convertToType(data['responses'], [SendDefinitionResponseItem]);
            }
        }
        return obj;
    }

    /**
    * The ID of the request
    * @member {String} requestId
    */
    requestId = undefined;
    /**
    * The specific error code
    * @member {Number} errorcode
    */
    errorcode = undefined;
    /**
    * 
    * @member {String} message
    */
    message = undefined;
    /**
    * 
    * @member {Array.<module:Model/SendDefinitionResponseItem>} responses
    */
    responses = undefined;








}


