/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');
const Attributes = require ('./Attributes');
const Recipient = require ('./Recipient');
const SendSmsContentRequest = require ('./SendSmsContentRequest');
const SendSmsToMultipleRecipientsSubscriptionsRequest = require ('./SendSmsToMultipleRecipientsSubscriptionsRequest');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The SendSmsToMultipleRecipientsRequest model module.
* @module Model/SendSmsToMultipleRecipientsRequest
* @version 1.0.0
*/
module.exports = class SendSmsToMultipleRecipientsRequest{
    /**
    * Constructs a new <code>SendSmsToMultipleRecipientsRequest</code>.
    * @alias module:Model/SendSmsToMultipleRecipientsRequest
    * @class
    * @param definitionKey {String} Unique, user-generated key to access the definition object.
    * @param recipients {Array.<module:Model/Recipient>} Array of recipient objects that contain parameters and metadata for the recipients, such as send tracking and personalization attributes. Use this parameter to send to multiple recipients in one request. Use either the recipient or recipients parameter, but not both.
    */

    constructor(definitionKey, recipients) {
        
        // verify the required parameter 'definitionKey' is set
        if(definitionKey === undefined || definitionKey === null){
            throw new InvalidModelException('"definitionKey" is a required property for SendSmsToMultipleRecipientsRequest and cannot be undefined or null');
        }
        this['definitionKey'] = definitionKey;
        
        // verify the required parameter 'recipients' is set
        if(recipients === undefined || recipients === null){
            throw new InvalidModelException('"recipients" is a required property for SendSmsToMultipleRecipientsRequest and cannot be undefined or null');
        }
        this['recipients'] = recipients;
        
        
        
        
    }

    /**
    * Constructs a <code>SendSmsToMultipleRecipientsRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/SendSmsToMultipleRecipientsRequest} obj Optional instance to populate.
    * @return {module:Model/SendSmsToMultipleRecipientsRequest} The populated <code>SendSmsToMultipleRecipientsRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendSmsToMultipleRecipientsRequest();

            
            
            

            if (data.hasOwnProperty('definitionKey')) {
                obj['definitionKey'] = ApiClient.convertToType(data['definitionKey'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = ApiClient.convertToType(data['recipients'], [Recipient]);
            }
            if (data.hasOwnProperty('subscriptions')) {
                obj['subscriptions'] = SendSmsToMultipleRecipientsSubscriptionsRequest.constructFromObject(data['subscriptions']);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = SendSmsContentRequest.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = Attributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
    * Unique, user-generated key to access the definition object.
    * @member {String} definitionKey
    */
    definitionKey = undefined;
    /**
    * Array of recipient objects that contain parameters and metadata for the recipients, such as send tracking and personalization attributes. Use this parameter to send to multiple recipients in one request. Use either the recipient or recipients parameter, but not both.
    * @member {Array.<module:Model/Recipient>} recipients
    */
    recipients = undefined;
    /**
    * @member {module:Model/SendSmsToMultipleRecipientsSubscriptionsRequest} subscriptions
    */
    subscriptions = undefined;
    /**
    * @member {module:Model/SendSmsContentRequest} content
    */
    content = undefined;
    /**
    * @member {module:Model/Attributes} attributes
    */
    attributes = undefined;








}


