/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The SendSmsContentRequest model module.
* @module Model/SendSmsContentRequest
* @version 1.0.0
*/
module.exports = class SendSmsContentRequest{
    /**
    * Constructs a new <code>SendSmsContentRequest</code>.
    * @alias module:Model/SendSmsContentRequest
    * @class
    */

    constructor() {
        
        
    }

    /**
    * Constructs a <code>SendSmsContentRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/SendSmsContentRequest} obj Optional instance to populate.
    * @return {module:Model/SendSmsContentRequest} The populated <code>SendSmsContentRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendSmsContentRequest();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * Override for message content in the definition that you want sent with each message. Use substitution strings to personalize the content.
    * @member {String} message
    */
    message = undefined;








}


