/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require ('../ApiClient');





const InvalidModelException = require('../Exception/InvalidModelException');

/**
* The SharingProperties model module.
* @module Model/SharingProperties
* @version 1.0.0
*/
module.exports = class SharingProperties{
    /**
    * Constructs a new <code>SharingProperties</code>.
    * @alias module:Model/SharingProperties
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SharingProperties</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/SharingProperties} obj Optional instance to populate.
    * @return {module:Model/SharingProperties} The populated <code>SharingProperties</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SharingProperties();

            
            
            

            if (data.hasOwnProperty('sharingType')) {
                obj['sharingType'] = ApiClient.convertToType(data['sharingType'], 'String');
            }
            if (data.hasOwnProperty('sharedWith')) {
                obj['sharedWith'] = ApiClient.convertToType(data['sharedWith'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * Indicates the permission that you are granting to the list of MIDs in sharedWith. Possible values are view, edit, or local.
    * @member {module:Model/SharingProperties.SharingTypeEnum} sharingType
    */
    sharingType = undefined;
    /**
    * List of MID IDs the asset is shared with
    * @member {Array.<Number>} sharedWith
    */
    sharedWith = undefined;






    /**
    * Allowed values for the <code>sharingType</code> property.
    * @enum {String}
    * @readonly
    */
    static SharingTypeEnum = {
    
        /**
         * value: "view"
         * @const
         */
        "view": "view",
    
        /**
         * value: "edit"
         * @const
         */
        "edit": "edit",
    
        /**
         * value: "local"
         * @const
         */
        "local": "local"    
    };



}


