/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require('./ApiClient');
const ApiError = require ('./Model/ApiError');
const Asset = require ('./Model/Asset');
const AssetType = require ('./Model/AssetType');
const Attributes = require ('./Model/Attributes');
const Campaign = require ('./Model/Campaign');
const CreateEmailDefinitionContent = require ('./Model/CreateEmailDefinitionContent');
const CreateEmailDefinitionOptionsRequest = require ('./Model/CreateEmailDefinitionOptionsRequest');
const CreateEmailDefinitionRequest = require ('./Model/CreateEmailDefinitionRequest');
const CreateEmailDefinitionSubscriptions = require ('./Model/CreateEmailDefinitionSubscriptions');
const CreateSmsDefinitionContent = require ('./Model/CreateSmsDefinitionContent');
const CreateSmsDefinitionRequest = require ('./Model/CreateSmsDefinitionRequest');
const CreateSmsDefinitionSubscriptions = require ('./Model/CreateSmsDefinitionSubscriptions');
const DeleteQueuedMessagesForSendDefinitionResponse = require ('./Model/DeleteQueuedMessagesForSendDefinitionResponse');
const DeleteSendDefinitionResponse = require ('./Model/DeleteSendDefinitionResponse');
const GetDefinitionSendStatusForRecipientResponse = require ('./Model/GetDefinitionSendStatusForRecipientResponse');
const GetDefinitionSendStatusForRecipientResponseInfo = require ('./Model/GetDefinitionSendStatusForRecipientResponseInfo');
const GetDefinitionsNotSentToRecipientsMessage = require ('./Model/GetDefinitionsNotSentToRecipientsMessage');
const GetDefinitionsNotSentToRecipientsMessageInfo = require ('./Model/GetDefinitionsNotSentToRecipientsMessageInfo');
const GetDefinitionsNotSentToRecipientsResponse = require ('./Model/GetDefinitionsNotSentToRecipientsResponse');
const GetEmailDefinitionsResponse = require ('./Model/GetEmailDefinitionsResponse');
const GetQueueMetricsForSendDefinitionResponse = require ('./Model/GetQueueMetricsForSendDefinitionResponse');
const GetSmsDefinitionsResponse = require ('./Model/GetSmsDefinitionsResponse');
const Recipient = require ('./Model/Recipient');
const SendDefinitionResponseItem = require ('./Model/SendDefinitionResponseItem');
const SendDefinitionToMultipleRecipientsResponse = require ('./Model/SendDefinitionToMultipleRecipientsResponse');
const SendDefinitionToSingleRecipientResponse = require ('./Model/SendDefinitionToSingleRecipientResponse');
const SendEmailToMultipleRecipientsRequest = require ('./Model/SendEmailToMultipleRecipientsRequest');
const SendEmailToSingleRecipientRequest = require ('./Model/SendEmailToSingleRecipientRequest');
const SendSmsContentRequest = require ('./Model/SendSmsContentRequest');
const SendSmsToMultipleRecipientsRequest = require ('./Model/SendSmsToMultipleRecipientsRequest');
const SendSmsToMultipleRecipientsSubscriptionsRequest = require ('./Model/SendSmsToMultipleRecipientsSubscriptionsRequest');
const SendSmsToSingleRecipientRequest = require ('./Model/SendSmsToSingleRecipientRequest');
const SharingProperties = require ('./Model/SharingProperties');
const UpdateEmailDefinitionRequest = require ('./Model/UpdateEmailDefinitionRequest');
const UpdateSmsDefinitionRequest = require ('./Model/UpdateSmsDefinitionRequest');
const AssetApi = require ('./Api/AssetApi');
const CampaignApi = require ('./Api/CampaignApi');
const TransactionalMessagingApi = require ('./Api/TransactionalMessagingApi');


/**
* Marketing_Clouds_REST_API_is_our_newest_API__It_supports_multi_channel_use_cases_is_much_more_lightweight_and_easy_to_use_than_our_SOAP_API_and_is_getting_more_comprehensive_with_every_release_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SalesforceMarketingCloud = require('index'); // See note below*.
* var xxxSvc = new SalesforceMarketingCloud.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SalesforceMarketingCloud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SalesforceMarketingCloud.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SalesforceMarketingCloud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
module.exports={
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiError model constructor.
     * @property {module:Model/ApiError}
     */
    ApiError,

    /**
     * The Asset model constructor.
     * @property {module:Model/Asset}
     */
    Asset,

    /**
     * The AssetType model constructor.
     * @property {module:Model/AssetType}
     */
    AssetType,

    /**
     * The Attributes model constructor.
     * @property {module:Model/Attributes}
     */
    Attributes,

    /**
     * The Campaign model constructor.
     * @property {module:Model/Campaign}
     */
    Campaign,

    /**
     * The CreateEmailDefinitionContent model constructor.
     * @property {module:Model/CreateEmailDefinitionContent}
     */
    CreateEmailDefinitionContent,

    /**
     * The CreateEmailDefinitionOptionsRequest model constructor.
     * @property {module:Model/CreateEmailDefinitionOptionsRequest}
     */
    CreateEmailDefinitionOptionsRequest,

    /**
     * The CreateEmailDefinitionRequest model constructor.
     * @property {module:Model/CreateEmailDefinitionRequest}
     */
    CreateEmailDefinitionRequest,

    /**
     * The CreateEmailDefinitionSubscriptions model constructor.
     * @property {module:Model/CreateEmailDefinitionSubscriptions}
     */
    CreateEmailDefinitionSubscriptions,

    /**
     * The CreateSmsDefinitionContent model constructor.
     * @property {module:Model/CreateSmsDefinitionContent}
     */
    CreateSmsDefinitionContent,

    /**
     * The CreateSmsDefinitionRequest model constructor.
     * @property {module:Model/CreateSmsDefinitionRequest}
     */
    CreateSmsDefinitionRequest,

    /**
     * The CreateSmsDefinitionSubscriptions model constructor.
     * @property {module:Model/CreateSmsDefinitionSubscriptions}
     */
    CreateSmsDefinitionSubscriptions,

    /**
     * The DeleteQueuedMessagesForSendDefinitionResponse model constructor.
     * @property {module:Model/DeleteQueuedMessagesForSendDefinitionResponse}
     */
    DeleteQueuedMessagesForSendDefinitionResponse,

    /**
     * The DeleteSendDefinitionResponse model constructor.
     * @property {module:Model/DeleteSendDefinitionResponse}
     */
    DeleteSendDefinitionResponse,

    /**
     * The GetDefinitionSendStatusForRecipientResponse model constructor.
     * @property {module:Model/GetDefinitionSendStatusForRecipientResponse}
     */
    GetDefinitionSendStatusForRecipientResponse,

    /**
     * The GetDefinitionSendStatusForRecipientResponseInfo model constructor.
     * @property {module:Model/GetDefinitionSendStatusForRecipientResponseInfo}
     */
    GetDefinitionSendStatusForRecipientResponseInfo,

    /**
     * The GetDefinitionsNotSentToRecipientsMessage model constructor.
     * @property {module:Model/GetDefinitionsNotSentToRecipientsMessage}
     */
    GetDefinitionsNotSentToRecipientsMessage,

    /**
     * The GetDefinitionsNotSentToRecipientsMessageInfo model constructor.
     * @property {module:Model/GetDefinitionsNotSentToRecipientsMessageInfo}
     */
    GetDefinitionsNotSentToRecipientsMessageInfo,

    /**
     * The GetDefinitionsNotSentToRecipientsResponse model constructor.
     * @property {module:Model/GetDefinitionsNotSentToRecipientsResponse}
     */
    GetDefinitionsNotSentToRecipientsResponse,

    /**
     * The GetEmailDefinitionsResponse model constructor.
     * @property {module:Model/GetEmailDefinitionsResponse}
     */
    GetEmailDefinitionsResponse,

    /**
     * The GetQueueMetricsForSendDefinitionResponse model constructor.
     * @property {module:Model/GetQueueMetricsForSendDefinitionResponse}
     */
    GetQueueMetricsForSendDefinitionResponse,

    /**
     * The GetSmsDefinitionsResponse model constructor.
     * @property {module:Model/GetSmsDefinitionsResponse}
     */
    GetSmsDefinitionsResponse,

    /**
     * The Recipient model constructor.
     * @property {module:Model/Recipient}
     */
    Recipient,

    /**
     * The SendDefinitionResponseItem model constructor.
     * @property {module:Model/SendDefinitionResponseItem}
     */
    SendDefinitionResponseItem,

    /**
     * The SendDefinitionToMultipleRecipientsResponse model constructor.
     * @property {module:Model/SendDefinitionToMultipleRecipientsResponse}
     */
    SendDefinitionToMultipleRecipientsResponse,

    /**
     * The SendDefinitionToSingleRecipientResponse model constructor.
     * @property {module:Model/SendDefinitionToSingleRecipientResponse}
     */
    SendDefinitionToSingleRecipientResponse,

    /**
     * The SendEmailToMultipleRecipientsRequest model constructor.
     * @property {module:Model/SendEmailToMultipleRecipientsRequest}
     */
    SendEmailToMultipleRecipientsRequest,

    /**
     * The SendEmailToSingleRecipientRequest model constructor.
     * @property {module:Model/SendEmailToSingleRecipientRequest}
     */
    SendEmailToSingleRecipientRequest,

    /**
     * The SendSmsContentRequest model constructor.
     * @property {module:Model/SendSmsContentRequest}
     */
    SendSmsContentRequest,

    /**
     * The SendSmsToMultipleRecipientsRequest model constructor.
     * @property {module:Model/SendSmsToMultipleRecipientsRequest}
     */
    SendSmsToMultipleRecipientsRequest,

    /**
     * The SendSmsToMultipleRecipientsSubscriptionsRequest model constructor.
     * @property {module:Model/SendSmsToMultipleRecipientsSubscriptionsRequest}
     */
    SendSmsToMultipleRecipientsSubscriptionsRequest,

    /**
     * The SendSmsToSingleRecipientRequest model constructor.
     * @property {module:Model/SendSmsToSingleRecipientRequest}
     */
    SendSmsToSingleRecipientRequest,

    /**
     * The SharingProperties model constructor.
     * @property {module:Model/SharingProperties}
     */
    SharingProperties,

    /**
     * The UpdateEmailDefinitionRequest model constructor.
     * @property {module:Model/UpdateEmailDefinitionRequest}
     */
    UpdateEmailDefinitionRequest,

    /**
     * The UpdateSmsDefinitionRequest model constructor.
     * @property {module:Model/UpdateSmsDefinitionRequest}
     */
    UpdateSmsDefinitionRequest,

    /**
    * The AssetApi service constructor.
    * @property {module:Api/AssetApi}
    */
    AssetApi,

    /**
    * The CampaignApi service constructor.
    * @property {module:Api/CampaignApi}
    */
    CampaignApi,

    /**
    * The TransactionalMessagingApi service constructor.
    * @property {module:Api/TransactionalMessagingApi}
    */
    TransactionalMessagingApi
};
